### ISSUE TITLE
Help with "out of memory" message

### ISSUE THREAD

**Issue by ClothingAI** [chflame163/ComfyUI_CatVTON_Wrapper#18]
Hey
I usually have a good GPU,
but I recently got a problem with pytorch library in comfyui so i tried to fix it and it seemed to work fine, 
but when I tried catVTON (which caused this problem with pytorch btw)
I got this error:
`!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "C:\Users\aaas\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.....
...
File "C:\Users\aaas\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\catvton\attn_processor.py", line 88, in __call__
    hidden_states = F.scaled_dot_product_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
`

I tried modifyin the choice of segmentation model in that particular node, but same result!
What is wrong?
Thanks

**Comment by kaishanguai2012** [comment]
same.Strangely, I successfully ran the workflow once and then encountered this issue when I ran it again.

**Comment by ClothingAI** [comment]
Yeah, I think I read inside another post a solution about changing a value on the catvon node, somethign about using fp16 or something.

**Comment by chflame163** [comment]
I tested  successfully on 16G VRAM Nvidia GPU
