### ISSUE TITLE
"Got an OOM, unloading all loaded models" 报错

### ISSUE THREAD

**Issue by li258w** [chflame163/ComfyUI_CatVTON_Wrapper#21]
got prompt
downloading https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_h.pth to D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\models\sams\sam_hq_vit_h.pth
100%|█████████████████████████████████████████████████████████████████████████████| 2.39G/2.39G [02:57<00:00, 14.5MB/s]
<All keys matched successfully>
# 😺dzNodes: LayerStyle -> SegmentAnythingUltra V2 Processed 1 image(s).
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\cat_vton.py", line 74, in catvton
    result_image = pipeline(
                   ^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\catvton\pipeline.py", line 163, in __call__
    noise_pred= self.unet(
                ^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d_condition.py", line 1216, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 1288, in forward
    hidden_states = attn(
                    ^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\diffusers\models\transformers\transformer_2d.py", line 442, in forward
    hidden_states = block(
                    ^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\diffusers\models\attention.py", line 466, in forward
    attn_output = self.attn1(
                  ^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\python_embeded\Lib\site-packages\diffusers\models\attention_processor.py", line 490, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows\ComfyUI_windows_portable-CatVTON_Wrapper\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\catvton\attn_processor.py", line 88, in __call__
    hidden_states = F.scaled_dot_product_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 196.35 seconds

**Comment by chflame163** [comment]
How much VRAM does your GPU have?

**Comment by zmwv823** [comment]
Use `ComfyUI-segment-anything-2` instead, SegmentAnything v1 custom_nodes never release the vram.
Only 3.0GB vram needed in inpaint process.
Mask and image can be conver to each other.
![image](https://github.com/user-attachments/assets/5f5cef36-f46f-47a0-98f9-b05971eeca46)
![image](https://github.com/user-attachments/assets/8cc41bb0-2a66-458d-87dc-0743649ef1e9)
Segment-anything-2
![image](https://github.com/user-attachments/assets/3eec9b09-5248-4091-b462-e7df6f019be1)

**Comment by lelamthanh** [comment]
I got this error today. I used workflow example, run on colab T4 (GPU 15 VRAM).
