### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.xpu'

### ISSUE THREAD

**Issue by hjcxlp** [chflame163/ComfyUI_CatVTON_Wrapper#25]
Traceback (most recent call last):
  File "D:\ComfyUI-G\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-G\custom_nodes\ComfyUI_CatVTON_Wrapper\__init__.py", line 31, in <module>
    imported_module = importlib.import_module(".py.{}".format(name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-G\.ext\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-G\custom_nodes\ComfyUI_CatVTON_Wrapper\py\cat_vton - 副本.py", line 1, in <module>
    import torch.xpu
ModuleNotFoundError: No module named 'torch.xpu'

pls advise how to fix this

**Comment by chflame163** [comment]
What is "D:\ComfyUI-G\custom_nodes\ComfyUI_CatVTON_Wrapper\py\cat_vton - 副本.py" ? Delete it.
