### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /root/ComfyUI/models/CatVTON/stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode

### ISSUE THREAD

**Issue by Jasonlin00** [chflame163/ComfyUI_CatVTON_Wrapper#33]
I downloaded all the models from Google Drive and placed them in the ComfyUI/models/CatVTON/ folder, but I still get this error.
i am using the latest ComfyUI and ComfyUI manager.
```
!!! Exception during processing !!! We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /root/ComfyUI/models/CatVTON/stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root/ComfyUI/models/CatVTON/stable-diffusion-inpainting'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper/py/cat_vton.py", line 47, in catvton
    pipeline = CatVTONPipeline(
  File "/root/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper/py/catvton/pipeline.py", line 41, in __init__
    self.noise_scheduler = DDIMScheduler.from_pretrained(base_ckpt, subfolder="scheduler")
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/diffusers/schedulers/scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/comfyui/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /root/ComfyUI/models/CatVTON/stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
```

**Comment by chflame163** [comment]
Perhaps model file was not fully downloaded, please confirm your network can access huggingface. co

**Comment by Jasonlin00** [comment]
> Perhaps model file was not fully downloaded, please confirm your network can access huggingface. co

i am using proxychains to run comfyui ,is that a problem?Everything else is normal

**Comment by chflame163** [comment]
I don't know

**Comment by glitzhigh** [comment]
I get the same error

**Comment by Jasonlin00** [comment]
> I get the same error

check the name of the CatVTON folder
